apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-{{ .Values.app.name }}-cluster-role
rules:
  - apiGroups:
      - "onecx.tkit.org"
    resources:
      - "slots"
      - "slots/status"
      - "slots/finalizers"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "patch"
      - "update"
      - "create"
      - "delete"
